--inserting the acdemic year and the level

INSERT INTO academics (
	academic_level
)
VALUES ('bachelors'),('masters'),('doctoral');

--inserting into academic year table

INSERT INTO academic_year (academic_year,academic_key)
VALUES (1,1),
       (2,1),
       (3,1),
       (4,1),
       (1,2),
       (2,2);


--inserting the majors in the majors table

INSERT INTO major (major_name) VALUES
('Accounting'),
('Adolescence to Young Adult Education'),
('Aerospace Engineering'),
('Applied Mathematical Economics'),
('Applied Mathematics'),
('Art History'),
('Arts & Humanities:'),
('BS)'),
('Biochemistry'),
('Bioengineering'),
('Biology'),
('Business Administration ('),
('Business Analytics'),
('Business Economics'),
('Chemical Engineering'),
('Chemistry'),
('Civil Engineering'),
('Clinical Mental Health Counseling'),
('Communication (Communication Management'),
('Communication Studies'),
('Computer Engineering'),
('Computer Information Systems'),
('Computer Science'),
('Criminal Justice and Security Studies'),
('Cyber Security'),
('Dance'),
('Dietetics'),
('Dietetics and Nutrition'),
('Discover Engineering and Discover Engineering Technology are also options for undecided engineering students.'),
('Doctoral Programs:'),
('Early Childhood Leadership and Advocacy'),
('Economics'),
('Educational Leadership'),
('Electrical Engineering'),
('Electro-Optics'),
('Engineering Management'),
('Engineering Mechanics'),
('Engineering Technology Programs (Electronic and Computer Engineering Technology'),
('English'),
('Entrepreneurship'),
('Environmental Biology'),
('Environmental Geology'),
('Finance'),
('Fine Arts'),
('French'),
('General Studies B.G.S.'),
('Geology'),
('German'),
('Graduate Majors:'),
('Graphic Design'),
('Health Science (Exercise and Movement Science'),
('Health and Fitness)'),
('Health and Wellness (Community Health'),
('Higher Education and Student Affairs'),
('History'),
('Human Rights Studies'),
('Human Services'),
('Industrial Engineering Technology'),
('Integrative Physiology)'),
('Interdisciplinary Educational Studies'),
('International Studies'),
('Intervention Specialist (Special Education) Pre-Kindergarten to Grade 5'),
('Journalism'),
('Leadership for Organizations'),
('Literacy'),
('Management'),
('Management Information Systems'),
('Marketing'),
('Marketing)'),
('Master of Laws'),
('Masters Programs ('),
('Materials Engineering'),
('Mathematics'),
('Mechanical Engineering'),
('Mechanical Engineering Technology)'),
('Media Production'),
('Medicinal-Pharmaceutical Chemistry'),
('Middle Childhood Education'),
('Multi-Age Education'),
('Music (Music Composition'),
('Music Education'),
('Music Performance'),
('Music Therapy'),
('Music Therapy)'),
('Natural Sciences & Mathematics:'),
('Nursing'),
('Operations and Supply Chain Management'),
('Other Bachelors Degrees:'),
('Pastoral Ministry'),
('Philosophy'),
('Photography'),
('Physical Science'),
('Physician Assistant Education'),
('Physics'),
('Physics-Computer Science'),
('Political Science'),
('Predentistry'),
('Premedicine'),
('Psychology (BA'),
('Public Administration'),
('Public Relations)'),
('Religious Studies'),
('Renewable and Clean Energy'),
('School Counseling'),
('School Psychology'),
('School of Business Administration:'),
('School of Education and Health Sciences:'),
('School of Engineering:'),
('Secondary Catholic Religion Education'),
('Social Sciences:'),
('Sociology'),
('Spanish'),
('Specialization in Transdisciplinary Early Childhood Education'),
('Sport Management'),
('Statistics'),
('Sustainability'),
('Systems Engineering'),
('Teacher Education (Adolescence to Young Adult Education'),
('Teacher as Leader'),
('Teaching English to Speakers of Other Languages'),
('Technology-Enhanced Learning'),
('The University of Dayton offers a variety of masters and doctoral programs. Some examples include:'),
('Theatre'),
('Theological Studies'),
('Transdisciplinary Early Childhood Education'),
('Visual Arts (Art Education'),
('Visual Arts)'),
('Womens and Gender Studies'),
('World Language Education)'),
('and Performance Technology'),
('with specializations like Business Analytics');
